/* The following code was generated by JFlex 1.4.3 on 11/6/14 4:21 PM */

package com.prezi.intellij.spaghetti;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static com.prezi.intellij.spaghetti.psi.SpaghettiModuleTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/6/14 4:21 PM from the specification file
 * <tt>/Users/balintgabor/prezi/workspace/spaghetti-idea-plugin/src/com/prezi/intellij/spaghetti/_SpaghettiModuleLexer.flex</tt>
 */
public class _SpaghettiModuleLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\2\1\0\1\1\1\1\22\0\1\1\1\0\1\12"+
    "\4\0\1\10\1\14\1\15\1\4\3\0\1\6\1\3\12\5\5\0"+
    "\1\13\1\0\1\20\21\7\1\21\7\7\1\0\1\11\2\0\1\7"+
    "\1\0\1\41\1\44\1\22\1\30\1\33\1\40\1\45\1\7\1\34"+
    "\2\7\1\32\1\27\1\24\1\23\1\35\1\7\1\36\1\25\1\26"+
    "\1\31\1\42\1\7\1\37\1\43\1\7\1\16\1\0\1\17\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\2\1\4\1\1\2\2\1\5"+
    "\1\6\1\7\1\10\1\11\14\1\1\12\1\0\1\13"+
    "\1\0\1\14\3\0\1\15\15\1\1\0\6\1\1\16"+
    "\3\1\1\17\2\1\1\20\1\0\1\1\1\21\2\1"+
    "\1\22\6\1\1\23\1\24\1\25\7\1\1\26\1\27"+
    "\1\30\1\31\1\32\1\1\1\33\1\1\1\34\1\35"+
    "\2\1\1\36";

  private static int [] zzUnpackAction() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\162\0\230\0\276\0\344\0\u010a"+
    "\0\46\0\46\0\46\0\46\0\46\0\u0130\0\u0156\0\u017c"+
    "\0\u01a2\0\u01c8\0\u01ee\0\u0214\0\u023a\0\u0260\0\u0286\0\u02ac"+
    "\0\u02d2\0\u02f8\0\u031e\0\u0344\0\344\0\46\0\u036a\0\u010a"+
    "\0\u0390\0\276\0\u03b6\0\u03dc\0\u0402\0\u0428\0\u044e\0\u0474"+
    "\0\u049a\0\u04c0\0\u04e6\0\u050c\0\u0532\0\u0558\0\u057e\0\u05a4"+
    "\0\u05ca\0\u05f0\0\u0616\0\u063c\0\u0662\0\u0688\0\u06ae\0\u06d4"+
    "\0\u06fa\0\u0720\0\276\0\u0746\0\u076c\0\46\0\u0792\0\u07b8"+
    "\0\276\0\u07de\0\u0804\0\276\0\u082a\0\u0850\0\u0876\0\u089c"+
    "\0\u08c2\0\u08e8\0\276\0\276\0\276\0\u090e\0\u0934\0\u095a"+
    "\0\u0980\0\u09a6\0\u09cc\0\u09f2\0\276\0\276\0\276\0\276"+
    "\0\276\0\u0a18\0\276\0\u0a3e\0\276\0\276\0\u0a64\0\u0a8a"+
    "\0\276";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\2\1\5\1\2\1\6\1\7"+
    "\1\2\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\6\1\17\1\6\1\20\1\21\1\22\1\23\3\6"+
    "\1\24\1\25\3\6\1\26\1\27\1\30\1\6\1\31"+
    "\1\6\47\0\2\3\46\0\1\32\1\33\46\0\1\5"+
    "\1\34\1\6\10\0\26\6\5\0\1\6\1\0\1\6"+
    "\10\0\26\6\10\35\1\36\1\37\34\35\11\40\1\41"+
    "\1\36\33\40\5\0\1\6\1\0\1\6\10\0\1\6"+
    "\1\42\24\6\5\0\1\6\1\0\1\6\10\0\3\6"+
    "\1\43\22\6\5\0\1\6\1\0\1\6\10\0\11\6"+
    "\1\44\14\6\5\0\1\6\1\0\1\6\10\0\6\6"+
    "\1\45\17\6\5\0\1\6\1\0\1\6\10\0\16\6"+
    "\1\46\7\6\5\0\1\6\1\0\1\6\10\0\3\6"+
    "\1\47\22\6\5\0\1\6\1\0\1\6\10\0\17\6"+
    "\1\50\6\6\5\0\1\6\1\0\1\6\10\0\4\6"+
    "\1\51\2\6\1\52\16\6\5\0\1\6\1\0\1\6"+
    "\10\0\12\6\1\53\6\6\1\54\4\6\5\0\1\6"+
    "\1\0\1\6\10\0\4\6\1\55\21\6\5\0\1\6"+
    "\1\0\1\6\10\0\3\6\1\56\22\6\5\0\1\6"+
    "\1\0\1\6\10\0\3\6\1\57\22\6\2\32\1\0"+
    "\43\32\4\33\1\60\41\33\5\0\1\34\40\0\2\35"+
    "\1\0\43\35\2\40\1\0\43\40\5\0\1\6\1\0"+
    "\1\6\10\0\4\6\1\61\21\6\5\0\1\6\1\0"+
    "\1\6\10\0\12\6\1\62\13\6\5\0\1\6\1\0"+
    "\1\6\10\0\16\6\1\63\7\6\5\0\1\6\1\0"+
    "\1\6\10\0\11\6\1\64\14\6\5\0\1\6\1\0"+
    "\1\6\10\0\10\6\1\65\15\6\5\0\1\6\1\0"+
    "\1\6\10\0\6\6\1\66\17\6\5\0\1\6\1\0"+
    "\1\6\10\0\6\6\1\67\17\6\5\0\1\6\1\0"+
    "\1\6\10\0\15\6\1\70\10\6\5\0\1\6\1\0"+
    "\1\6\10\0\3\6\1\71\22\6\5\0\1\6\1\0"+
    "\1\6\10\0\12\6\1\72\13\6\5\0\1\6\1\0"+
    "\1\6\10\0\23\6\1\73\2\6\5\0\1\6\1\0"+
    "\1\6\10\0\14\6\1\74\11\6\5\0\1\6\1\0"+
    "\1\6\10\0\3\6\1\75\22\6\3\33\1\76\1\77"+
    "\41\33\5\0\1\6\1\0\1\6\10\0\5\6\1\100"+
    "\20\6\5\0\1\6\1\0\1\6\10\0\12\6\1\101"+
    "\13\6\5\0\1\6\1\0\1\6\10\0\11\6\1\102"+
    "\2\6\1\103\11\6\5\0\1\6\1\0\1\6\10\0"+
    "\13\6\1\104\12\6\5\0\1\6\1\0\1\6\10\0"+
    "\11\6\1\105\14\6\5\0\1\6\1\0\1\6\10\0"+
    "\13\6\1\106\12\6\5\0\1\6\1\0\1\6\10\0"+
    "\13\6\1\107\12\6\5\0\1\6\1\0\1\6\10\0"+
    "\3\6\1\110\22\6\5\0\1\6\1\0\1\6\10\0"+
    "\21\6\1\111\4\6\5\0\1\6\1\0\1\6\10\0"+
    "\5\6\1\112\20\6\5\0\1\6\1\0\1\6\10\0"+
    "\10\6\1\113\15\6\5\0\1\6\1\0\1\6\10\0"+
    "\12\6\1\114\13\6\3\33\1\0\1\77\41\33\5\0"+
    "\1\6\1\0\1\6\10\0\6\6\1\115\17\6\5\0"+
    "\1\6\1\0\1\6\10\0\2\6\1\116\23\6\5\0"+
    "\1\6\1\0\1\6\10\0\4\6\1\117\21\6\5\0"+
    "\1\6\1\0\1\6\10\0\12\6\1\120\13\6\5\0"+
    "\1\6\1\0\1\6\10\0\4\6\1\121\11\6\1\122"+
    "\7\6\5\0\1\6\1\0\1\6\10\0\16\6\1\123"+
    "\7\6\5\0\1\6\1\0\1\6\10\0\16\6\1\124"+
    "\7\6\5\0\1\6\1\0\1\6\10\0\6\6\1\125"+
    "\17\6\5\0\1\6\1\0\1\6\10\0\13\6\1\126"+
    "\12\6\5\0\1\6\1\0\1\6\10\0\6\6\1\127"+
    "\17\6\5\0\1\6\1\0\1\6\10\0\25\6\1\130"+
    "\5\0\1\6\1\0\1\6\10\0\13\6\1\131\12\6"+
    "\5\0\1\6\1\0\1\6\10\0\10\6\1\132\15\6"+
    "\5\0\1\6\1\0\1\6\10\0\4\6\1\133\21\6"+
    "\5\0\1\6\1\0\1\6\10\0\20\6\1\134\5\6"+
    "\5\0\1\6\1\0\1\6\10\0\6\6\1\135\17\6"+
    "\5\0\1\6\1\0\1\6\10\0\5\6\1\136\20\6"+
    "\5\0\1\6\1\0\1\6\10\0\21\6\1\137\4\6"+
    "\5\0\1\6\1\0\1\6\10\0\2\6\1\140\23\6"+
    "\5\0\1\6\1\0\1\6\10\0\13\6\1\141\12\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2736];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\6\1\5\11\15\1\1\0\1\1\1\0"+
    "\1\11\3\0\16\1\1\0\15\1\1\11\1\0\42\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public _SpaghettiModuleLexer() {
    this((java.io.Reader)null);
  }


  public _SpaghettiModuleLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _SpaghettiModuleLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 120) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 14: 
          { return INT;
          }
        case 31: break;
        case 6: 
          { return PL;
          }
        case 32: break;
        case 17: 
          { return NULL;
          }
        case 33: break;
        case 10: 
          { return LINE_COMMENT;
          }
        case 34: break;
        case 7: 
          { return PR;
          }
        case 35: break;
        case 13: 
          { return AS;
          }
        case 36: break;
        case 11: 
          { return FLOATVALUE;
          }
        case 37: break;
        case 5: 
          { return OPTIONAL;
          }
        case 38: break;
        case 2: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 39: break;
        case 23: 
          { return FALSE;
          }
        case 40: break;
        case 20: 
          { return BOOL;
          }
        case 41: break;
        case 29: 
          { return EXTENDS;
          }
        case 42: break;
        case 16: 
          { return BLOCK_COMMENT;
          }
        case 43: break;
        case 1: 
          { return ID;
          }
        case 44: break;
        case 15: 
          { return ANY;
          }
        case 45: break;
        case 30: 
          { return INTERFACE;
          }
        case 46: break;
        case 22: 
          { return FLOAT;
          }
        case 47: break;
        case 19: 
          { return VOID;
          }
        case 48: break;
        case 4: 
          { return INTVALUE;
          }
        case 49: break;
        case 12: 
          { return STRINGVALUE;
          }
        case 50: break;
        case 25: 
          { return STRING;
          }
        case 51: break;
        case 28: 
          { return IMPORT;
          }
        case 52: break;
        case 26: 
          { return MODULE;
          }
        case 53: break;
        case 27: 
          { return EXTERN;
          }
        case 54: break;
        case 8: 
          { return CL;
          }
        case 55: break;
        case 24: 
          { return STRUCT;
          }
        case 56: break;
        case 18: 
          { return TRUE;
          }
        case 57: break;
        case 9: 
          { return CR;
          }
        case 58: break;
        case 3: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 59: break;
        case 21: 
          { return CONST;
          }
        case 60: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
