/* The following code was generated by JFlex 1.4.3 on 11/7/14 12:27 PM */

package com.prezi.intellij.spaghetti;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static com.prezi.intellij.spaghetti.psi.SpaghettiModuleTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/7/14 12:27 PM from the specification file
 * <tt>/Users/balintgabor/prezi/workspace/spaghetti-idea-plugin/src/com/prezi/intellij/spaghetti/_SpaghettiModuleLexer.flex</tt>
 */
public class _SpaghettiModuleLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\2\1\0\1\1\1\1\22\0\1\1\1\0\1\12"+
    "\4\0\1\10\1\14\1\15\1\4\3\0\1\6\1\3\12\5\5\0"+
    "\1\13\1\0\32\7\1\0\1\11\2\0\1\7\1\0\1\20\1\42"+
    "\1\22\1\27\1\32\1\37\1\43\1\7\1\33\2\7\1\31\1\26"+
    "\1\24\1\23\1\34\1\7\1\35\1\21\1\25\1\30\1\40\1\7"+
    "\1\36\1\41\1\7\1\16\1\0\1\17\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\2\1\4\1\1\2\2\1\5"+
    "\1\6\1\7\1\10\1\11\13\1\1\12\1\0\1\13"+
    "\1\0\1\14\3\0\1\15\16\1\1\0\1\16\7\1"+
    "\1\17\5\1\1\12\3\1\1\20\1\21\1\1\1\22"+
    "\5\1\1\23\1\24\2\1\1\25\5\1\1\26\1\27"+
    "\1\30\1\31\1\32\1\1\1\33\1\1\1\34\1\35"+
    "\2\1\1\36";

  private static int [] zzUnpackAction() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\264\0\330\0\374"+
    "\0\44\0\44\0\44\0\44\0\44\0\u0120\0\u0144\0\u0168"+
    "\0\u018c\0\u01b0\0\u01d4\0\u01f8\0\u021c\0\u0240\0\u0264\0\u0288"+
    "\0\u02ac\0\u02d0\0\u02f4\0\330\0\44\0\u0318\0\374\0\u033c"+
    "\0\264\0\u0360\0\u0384\0\u03a8\0\u03cc\0\u03f0\0\u0414\0\u0438"+
    "\0\u045c\0\u0480\0\u04a4\0\u04c8\0\u04ec\0\u0510\0\u0534\0\u0558"+
    "\0\264\0\u057c\0\u05a0\0\u05c4\0\u05e8\0\u060c\0\u0630\0\u0654"+
    "\0\u0678\0\u069c\0\u06c0\0\u06e4\0\u0708\0\u072c\0\44\0\u0750"+
    "\0\u0774\0\u0798\0\264\0\264\0\u07bc\0\264\0\u07e0\0\u0804"+
    "\0\u0828\0\u084c\0\u0870\0\264\0\264\0\u0894\0\u08b8\0\264"+
    "\0\u08dc\0\u0900\0\u0924\0\u0948\0\u096c\0\264\0\264\0\264"+
    "\0\264\0\264\0\u0990\0\264\0\u09b4\0\264\0\264\0\u09d8"+
    "\0\u09fc\0\264";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\2\1\5\1\2\1\6\1\7"+
    "\1\2\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\6\1\21\1\22\1\23\3\6\1\24"+
    "\1\25\3\6\1\26\1\27\1\6\1\30\1\6\45\0"+
    "\2\3\44\0\1\31\1\32\44\0\1\5\1\33\1\6"+
    "\10\0\24\6\5\0\1\6\1\0\1\6\10\0\24\6"+
    "\10\34\1\35\1\36\32\34\11\37\1\40\1\35\31\37"+
    "\5\0\1\6\1\0\1\6\10\0\1\6\1\41\2\6"+
    "\1\42\17\6\5\0\1\6\1\0\1\6\10\0\5\6"+
    "\1\43\16\6\5\0\1\6\1\0\1\6\10\0\3\6"+
    "\1\44\20\6\5\0\1\6\1\0\1\6\10\0\10\6"+
    "\1\45\13\6\5\0\1\6\1\0\1\6\10\0\15\6"+
    "\1\46\6\6\5\0\1\6\1\0\1\6\10\0\3\6"+
    "\1\47\20\6\5\0\1\6\1\0\1\6\10\0\4\6"+
    "\1\50\11\6\1\51\5\6\5\0\1\6\1\0\1\6"+
    "\10\0\4\6\1\52\1\6\1\53\15\6\5\0\1\6"+
    "\1\0\1\6\10\0\1\54\10\6\1\55\12\6\5\0"+
    "\1\6\1\0\1\6\10\0\3\6\1\56\20\6\5\0"+
    "\1\6\1\0\1\6\10\0\3\6\1\57\20\6\2\31"+
    "\1\0\41\31\4\32\1\60\37\32\5\0\1\33\36\0"+
    "\2\34\1\0\41\34\2\37\1\0\41\37\5\0\1\6"+
    "\1\0\1\6\10\0\21\6\1\61\2\6\5\0\1\6"+
    "\1\0\1\6\10\0\15\6\1\62\6\6\5\0\1\6"+
    "\1\0\1\6\10\0\4\6\1\63\17\6\5\0\1\6"+
    "\1\0\1\6\10\0\11\6\1\64\12\6\5\0\1\6"+
    "\1\0\1\6\10\0\10\6\1\65\13\6\5\0\1\6"+
    "\1\0\1\6\10\0\7\6\1\66\14\6\5\0\1\6"+
    "\1\0\1\6\10\0\10\6\1\67\13\6\5\0\1\6"+
    "\1\0\1\6\10\0\5\6\1\70\16\6\5\0\1\6"+
    "\1\0\1\6\10\0\5\6\1\71\16\6\5\0\1\6"+
    "\1\0\1\6\10\0\14\6\1\72\7\6\5\0\1\6"+
    "\1\0\1\6\10\0\11\6\1\73\12\6\5\0\1\6"+
    "\1\0\1\6\10\0\3\6\1\74\20\6\5\0\1\6"+
    "\1\0\1\6\10\0\13\6\1\75\10\6\5\0\1\6"+
    "\1\0\1\6\10\0\3\6\1\76\20\6\3\32\1\77"+
    "\1\60\37\32\5\0\1\6\1\0\1\6\10\0\10\6"+
    "\1\100\2\6\1\101\10\6\5\0\1\6\1\0\1\6"+
    "\10\0\1\6\1\102\22\6\5\0\1\6\1\0\1\6"+
    "\10\0\11\6\1\103\12\6\5\0\1\6\1\0\1\6"+
    "\10\0\12\6\1\104\11\6\5\0\1\6\1\0\1\6"+
    "\10\0\10\6\1\105\13\6\5\0\1\6\1\0\1\6"+
    "\10\0\6\6\1\106\15\6\5\0\1\6\1\0\1\6"+
    "\10\0\12\6\1\107\11\6\5\0\1\6\1\0\1\6"+
    "\10\0\12\6\1\110\11\6\5\0\1\6\1\0\1\6"+
    "\10\0\3\6\1\111\20\6\5\0\1\6\1\0\1\6"+
    "\10\0\1\6\1\112\22\6\5\0\1\6\1\0\1\6"+
    "\10\0\1\113\23\6\5\0\1\6\1\0\1\6\10\0"+
    "\7\6\1\114\14\6\5\0\1\6\1\0\1\6\10\0"+
    "\11\6\1\115\12\6\5\0\1\6\1\0\1\6\10\0"+
    "\2\6\1\116\21\6\5\0\1\6\1\0\1\6\10\0"+
    "\4\6\1\117\17\6\5\0\1\6\1\0\1\6\10\0"+
    "\5\6\1\120\16\6\5\0\1\6\1\0\1\6\10\0"+
    "\11\6\1\121\12\6\5\0\1\6\1\0\1\6\10\0"+
    "\4\6\1\122\10\6\1\123\6\6\5\0\1\6\1\0"+
    "\1\6\10\0\15\6\1\124\6\6\5\0\1\6\1\0"+
    "\1\6\10\0\15\6\1\125\6\6\5\0\1\6\1\0"+
    "\1\6\10\0\12\6\1\126\11\6\5\0\1\6\1\0"+
    "\1\6\10\0\5\6\1\127\16\6\5\0\1\6\1\0"+
    "\1\6\10\0\5\6\1\130\16\6\5\0\1\6\1\0"+
    "\1\6\10\0\23\6\1\131\5\0\1\6\1\0\1\6"+
    "\10\0\12\6\1\132\11\6\5\0\1\6\1\0\1\6"+
    "\10\0\7\6\1\133\14\6\5\0\1\6\1\0\1\6"+
    "\10\0\4\6\1\134\17\6\5\0\1\6\1\0\1\6"+
    "\10\0\17\6\1\135\4\6\5\0\1\6\1\0\1\6"+
    "\10\0\5\6\1\136\16\6\5\0\1\6\1\0\1\6"+
    "\10\0\1\6\1\137\22\6\5\0\1\6\1\0\1\6"+
    "\10\0\1\140\23\6\5\0\1\6\1\0\1\6\10\0"+
    "\2\6\1\141\21\6\5\0\1\6\1\0\1\6\10\0"+
    "\12\6\1\142\11\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2592];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\6\1\5\11\14\1\1\0\1\1\1\0"+
    "\1\11\3\0\17\1\1\0\16\1\1\11\43\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public _SpaghettiModuleLexer() {
    this((java.io.Reader)null);
  }


  public _SpaghettiModuleLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _SpaghettiModuleLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 114) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 15: 
          { return INT;
          }
        case 31: break;
        case 6: 
          { return PL;
          }
        case 32: break;
        case 16: 
          { return NULL;
          }
        case 33: break;
        case 10: 
          { return COMMENT;
          }
        case 34: break;
        case 7: 
          { return PR;
          }
        case 35: break;
        case 13: 
          { return AS;
          }
        case 36: break;
        case 11: 
          { return FLOATVALUE;
          }
        case 37: break;
        case 5: 
          { return OPTIONAL;
          }
        case 38: break;
        case 2: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 39: break;
        case 22: 
          { return FALSE;
          }
        case 40: break;
        case 20: 
          { return BOOL;
          }
        case 41: break;
        case 29: 
          { return EXTENDS;
          }
        case 42: break;
        case 1: 
          { return ID;
          }
        case 43: break;
        case 14: 
          { return ANY;
          }
        case 44: break;
        case 30: 
          { return INTERFACE;
          }
        case 45: break;
        case 23: 
          { return FLOAT;
          }
        case 46: break;
        case 19: 
          { return VOID;
          }
        case 47: break;
        case 4: 
          { return INTVALUE;
          }
        case 48: break;
        case 12: 
          { return STRINGVALUE;
          }
        case 49: break;
        case 25: 
          { return STRING;
          }
        case 50: break;
        case 18: 
          { return ENUM;
          }
        case 51: break;
        case 28: 
          { return IMPORT;
          }
        case 52: break;
        case 26: 
          { return MODULE;
          }
        case 53: break;
        case 27: 
          { return EXTERN;
          }
        case 54: break;
        case 8: 
          { return CL;
          }
        case 55: break;
        case 24: 
          { return STRUCT;
          }
        case 56: break;
        case 17: 
          { return TRUE;
          }
        case 57: break;
        case 9: 
          { return CR;
          }
        case 58: break;
        case 3: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 59: break;
        case 21: 
          { return CONST;
          }
        case 60: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
